language: node_js
node_js:
  - "22.12"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools

script:
  - npm run lint
  - npm run build
  - npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
  - npx playwright install --with-deps chromium
  - npm run e2e

after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
